seamapi/javascript

src/lib/api-error.ts

Closes https://github.com/seamapi/seamapi-javascript/issues/30.
@seveibar does this look better or did you have something else in mind? `.toString()` now looks like:
```
SeamMalformedInputError: {␊
"_errors": [],␊
"device_id": {␊
"_errors": [␊
"Invalid uuid"␊
]␊
}␊
}
```

Better formatting of validation errors

---

README.md

This proposes a possible fix for the broken "some examples" link at the top of https://github.com/seamapi/javascript/blob/main/README.md.
The paragraph with the examples link appears to have been copied, in commit adbaadba72d8129cb83ace689fecf8b1d2f3f706, from the python repo's readme. The python repo has an [examples directory](https://github.com/seamapi/python/tree/main/examples), so the link there works. But, the examples for the javascript repo are in the readme under the Usage heading (added by PR https://github.com/seamapi/javascript/pull/4).
My proposed fix is to swap the link to the non-existent examples directory for a list of links to Usage subheading anchors in the readme.

Fix broken "some examples" readme link

---

tests/fixtures/workers/helpers/start-and-seed-server.ts

The same thing had to be done with the Python SDK. Chances are, these GH tests will fail, too.

fix #66: Adjust Docker container reference

---

tests/webhooks.test.ts

`event_types` aren't working on seam connect at the moment, so this test can't subscribe properly to `access_code.created` w/o subscribing to `access_code.changed`

Skiptest until seam connect issue resolved

---

docs/interfaces/AccessCodeBase.md
docs/interfaces/ActionAttemptResultTypeMap.md
docs/interfaces/ActionAttemptWithError.md
docs/interfaces/ConnectWebview.md
docs/interfaces/ConnectedAccount.md
docs/interfaces/LockProperties.md
docs/interfaces/OngoingAccessCode.md
docs/interfaces/PendingActionAttempt.md
docs/interfaces/SuccessfulActionAttempt.md
docs/interfaces/TimeBoundAccessCode.md
docs/interfaces/UserIdentifier.md
docs/interfaces/Webhook.md
docs/modules.md
src/types/models.ts

- feat: Add filters to Devices List (#44)
- chore(release): 4.0.0 [skip ci]
- feat: Add accessCodes.update (#46)
- chore(release): 4.1.0 [skip ci]
- feat: Implemented webhooks endpoints (#47)
- chore(release): 4.2.0 [skip ci]
- Fix test
- feat: Add request retries (#43)
- chore(release): 4.3.0 [skip ci]
- fix: bump seamapi-types
- chore(release): 4.3.1 [skip ci]
- feat: add events list request (#48)
- chore(release): 4.4.0 [skip ci]
- fix: device typings
- chore(release): 4.4.1 [skip ci]
- feat: allow passing custom Axios options
- chore(release): 4.5.0 [skip ci]
- Use ghcr.io
- Fix org name
- Login after checkout?
- Login with bot token
- fix: Add `has_keypad` property
- chore(release): 4.6.0 [skip ci]
- fix #66: Adjust Docker container reference
- chore(release): 4.6.1 [skip ci]
- fix …

Add has_direct_power property on LockProperties

---

docs/modules.md
package.json
src/types/models.ts
tests/webhooks.test.ts
yarn.lock

Typescript doesn't bundle types from seamapi-types, meaning that unless a consumer also installs seamapi-types `events.list(...)` will return `Promise<any[]>`.

feat: Add event_id to event response, move seamapi-types to prod dependencies

---

docs/classes/Seam.md
package.json
src/seam-connect/routes.ts
tests/errors.test.ts
tests/fixtures/workers/helpers/get-test-database.ts
tests/fixtures/workers/helpers/get-test-svix.ts
tests/fixtures/workers/helpers/start-and-seed-server.ts
tests/routes.test.ts
yarn.lock

I would like to isolate these AVA updates and mark the tests failing here so the tests can be fixed in followup PRs. New issue here: https://github.com/seamapi/javascript/issues/110
- Update to AVA v5
- Update to testcontainers v9
- Note UPSTREAM issue
- Mark failing tests
- Fix local test issue with existing API key in env

test: Update test tooling and mark failing tests

---

docs/interfaces/AccessCodeBase.md
docs/interfaces/ActionAttemptResultTypeMap.md
docs/interfaces/ActionAttemptWithError.md
docs/interfaces/ConnectWebview.md
docs/interfaces/ConnectedAccount.md
docs/interfaces/LockProperties.md
docs/interfaces/OngoingAccessCode.md
docs/interfaces/PendingActionAttempt.md
docs/interfaces/SuccessfulActionAttempt.md
docs/interfaces/TimeBoundAccessCode.md
docs/interfaces/UserIdentifier.md
docs/interfaces/Webhook.md
docs/modules.md
src/types/models.ts
tests/routes.test.ts

Need to double check if this should be `model: string` or `model?: string` or maybe `model: string | null`?
Fixes the 3 tests in https://github.com/seamapi/javascript/issues/110

feat: Add model to device metadata

---

tests/errors.test.ts

Looks like the default behavior of the API changed to return an API error on duplicate code. We can merge this to fix the test.
Does this mean there is a breaking change on the API that caused this regression in the SDK?
Fixes one of the tests in https://github.com/seamapi/javascript/issues/110

Expect SeamAPIError on duplicate code

---

package.json
patches/ava+5.1.0.patch
yarn.lock

See https://github.com/avajs/ava/pull/3151.
Will create a new issue to remove this patch after merging.

Add temporary AVA patch

---

docs/interfaces/ConnectedAccount.md
docs/interfaces/UnmanagedAccessCode.md
docs/interfaces/UserIdentifier.md
docs/interfaces/Webhook.md
docs/modules.md
src/types/models.ts

Just had a chat with @rchodava, we do in fact support `time_bound` unmanaged codes now
See this test in connect which assumes that we support start and end times
[https://github.com/seamapi/seam-connect/commit/873456fc78d26db400c03367edae0d582f0b7375#diff-27980da6c4e3d3c609f50b1[…]483e7b9cc1517d146764bfR85-R86](https://github.com/seamapi/seam-connect/commit/873456fc78d26db400c03367edae0d582f0b7375#diff-27980da6c4e3d3c609f50b1b3b6c2b384bb0892f95483e7b9cc1517d146764bfR85-R86)

fix: update unmanaged access codes type

---

docs/classes/Seam.md
src/seam-connect/client.ts

Favor sending the `client-session-token` header for client session auth.

feat: Use client-session-token header

---

docs/classes/Seam.md
src/seam-connect/client.ts

- [Normalize getClientSessionToken options type](https://github.com/seamapi/javascript/pull/191/commits/37cc03f8212cd942625329d381bbd6cc4bebe606): Removes type to bring options into function signature and uses non-abbreviated arg name.
- [feat: Add checks for keys on getClientSessionToken](https://github.com/seamapi/javascript/pull/191/commits/fe72bad584d53323ffe26a2e10a38ae854189eaa): Throw error if keys prefix does not match expected prefix.
- [feat: Reuse makeRequest](https://github.com/seamapi/javascript/pull/191/commits/2bd1a40882ae5755c92131f1c449990d99c358f5): https://github.com/seamapi/javascript/issues/184
- [Move getAuthHeaders down](https://github.com/seamapi/javascript/pull/191/commits/cb8c00e526dbdb15e1c334c65ec6e7d776250141): Just move the helper below the caller.
- [fix: …

Improvements to client session methods 

---

docs/interfaces/AccessCodeBase.md
docs/interfaces/ManagedAccessCodeBase.md
docs/interfaces/OngoingAccessCode.md
docs/interfaces/TimeBoundAccessCode.md
docs/interfaces/UnmanagedAccessCodeBase.md
docs/interfaces/UnmanagedOngoingAccessCode.md
docs/interfaces/UnmanagedTimeBoundAccessCode.md
src/types/models.ts

Merging this separately from https://github.com/seamapi/javascript/pull/228

fix: Access code errors and warnings are non-optional

---

.github/actions/setup/action.yml
.github/workflows/_build.yml
.github/workflows/check.yml
.github/workflows/npm-test.yml
package.json
yarn.lock

Now I'm thinking it was really an issue with tsup. I am adding a check workflow for build and disabling the test workflow until we can fix it.

fix: Update tsup to fix build

---

.github/actions/setup/action.yml
.github/workflows/npm-semantic-release.yml
package.json

Something with the cache + npx on GH actions is breaking. We should be using the local version via what is installed with yarn instead anyway.

fix: Always use local semantic-release

---

.github/workflows/npm-semantic-release.yml
package.json

Now SR is saying the npm token is invalid. Going back to the npx method to see if that actually is related to this issue.

fix: Use npx for semantic-release

---

.github/workflows/npm-prettier.yml
.github/workflows/npm-semantic-release.yml
.github/workflows/npm-test.yml

This is the last known working semantic release workflow but without the cache options in any of the steps as that was randomly breaking the build.

fix: Use last known working workflow for npm-semantic-release

---

docs/classes/Seam.md
docs/interfaces/ClimateSettingScheduleCreateResponse.md
docs/interfaces/ClimateSettingScheduleGetResponse.md
docs/interfaces/ClimateSettingScheduleUpdateResponse.md
docs/interfaces/ClimateSettingSchedulesListResponse.md
docs/interfaces/ThermostatGetResponse.md
docs/interfaces/ThermostatsListResponse.md
docs/modules.md
src/seam-connect/routes.ts
src/types/route-requests.ts
src/types/route-responses.ts

- [fix: Add properly names client session types](https://github.com/seamapi/javascript/pull/240/commits/8732c0fa9ecc2988e25b6818f16be2e5b31dbb91)
- [feat: Add clientSessions.delete](https://github.com/seamapi/javascript/pull/240/commits/2353bc6a91d8c23f3a01443e1ab48559b8363794)
- [feat: Add clientSessions.list](https://github.com/seamapi/javascript/pull/240/commits/aba7e5feb902d75505015e561c6b641a2d8c658d)

Add missing client session methods

---

src/seam-connect/routes.ts

The API was ignoring the data passed as URL parameters but takes it into account when passed in the body.
https://axios-http.com/docs/req_config
- Axios's `params` sets URL parameters
- What the API seems to be expecting here is the body of the request to contain the data
@razor-x

Fix Session creation requests: data is expected in the request body

---

docs/interfaces/EventGetRequest.md
docs/interfaces/EventsListRequest.md
docs/modules.md
src/types/route-requests.ts

Currently hitting type blocks updating the endpoint for space-backend. Looks like this is a supported property in Connect.

fix: Add `type` property to `AccessCodeUpdateBaseRequest`

---

docs/classes/Seam.md
src/seam-connect/client.ts

I think using the custom header may have been a mistake and is partially responsible for the CORS cache issues. Using the `authorization` header should be more compatible with various protocol layers and give more predictable behavior. We can send both here as a test. We cannot remove the other one yet since CORS behavior depends on the presence of that header.

Use authorization header with client session token

---

package.json

Mainly because semantic release is stuck.

fix: Update package description

---

docs/classes/Seam.md
src/seam-connect/client.ts

This reverts commit d21b19292053609f873b8e02c837db3af934d178.

Revert "fix: Use authorization header with client session token (#253)"

---

docs/interfaces/AccessCodeCreateBaseRequest.md
docs/interfaces/AccessCodeCreateMultipleOngoingRequest.md
docs/interfaces/AccessCodeCreateMultipleScheduledRequest.md
docs/interfaces/AccessCodeCreateOngoingRequest.md
docs/interfaces/AccessCodeCreateScheduledRequest.md
docs/interfaces/AccessCodeUpdateBaseRequest.md
docs/interfaces/ConnectWebviewCreateRequest.md
docs/interfaces/ConnectWebviewDeleteRequest.md
docs/interfaces/ConnectedAccountsDeleteRequest.md
docs/interfaces/ConnectedAccountsGetRequest.md
docs/interfaces/DeviceProvidersListRequest.md
docs/interfaces/DevicesListRequest.md
docs/interfaces/EventGetRequest.md
docs/interfaces/EventsListRequest.md
docs/modules.md
src/types/route-requests.ts
tests/routes.test.ts

I believe this has always been optional
https://github.com/seamapi/seam-connect/blob/main/pages/api/public/thermostats/climate_setting_schedules/get.ts#L14

device_id is optional for /thermostats/climate_setting_schedules/get

---

docs/interfaces/EventGetRequest.md
docs/interfaces/EventsListRequest.md
docs/modules.md
src/types/route-requests.ts

Update `AccessCodesListRequest` type to allow both `device_id` and `access_code_ids` requiring at least one

---

docs/classes/Seam.md
docs/interfaces/SeamClientOptions.md
docs/modules.md
src/lib/params-serializer.ts
src/seam-connect/client.ts
tests/params-serializer.test.ts

Added paramsSerializer from https://github.com/seamapi/javascript-http/pull/8 to Seam client.
Fixes: https://github.com/seamapi/javascript/issues/251

fix: Serialize array params for GET requests

---

docs/interfaces/AccessCodeBase.md
docs/interfaces/AccessCodeError.md
docs/interfaces/ActionAttemptResultTypeMap.md
docs/interfaces/ActionAttemptWithError.md
docs/interfaces/BaseThermostatDeviceProperties.md
docs/interfaces/ClientSession.md
docs/interfaces/ConnectWebview.md
docs/interfaces/ConnectedAccount.md
docs/interfaces/ConnectedAccountError.md
docs/interfaces/Device.md
docs/interfaces/DeviceError.md
docs/interfaces/DeviceModel.md
docs/interfaces/DeviceProvider.md
docs/interfaces/LockProperties.md
docs/interfaces/ManagedAccessCodeBase.md
docs/interfaces/NoiseSensorDeviceProperties.md
docs/interfaces/OngoingAccessCode.md
docs/interfaces/PendingActionAttempt.md
docs/interfaces/SeamError.md
docs/interfaces/SeamWarning.md
docs/interfaces/SuccessfulActionAttempt.md
docs/interfaces/TimeBoundAccessCode.md
docs/interfaces/UnmanagedAccessCodeBase.md
docs/interfaces/UnmanagedOngoingAccessCode.md
docs/interfaces/UnmanagedTimeBoundAccessCode.md
docs/interfaces/UserIdentifier.md
docs/interfaces/Webhook.md
docs/modules.md
src/types/models.ts

Add provider metadata types to `NoiseSensorDeviceProperties`—needed in Seam Components which still uses this lib

fix: Add provider metadata to `NoiseSensorDeviceProperties`
