seamapi/javascript

README.md, docs/README.md, docs/interfaces/AccessCode.md, docs/interfaces/ConnectWebview.md, src/types/models.ts, yarn.lock
- usage example added to readme
- url added to ConnectWebview type
=> Usage example for readme

README.md, docs/README.md
Related to #10 never releasing :shrug:
=> Update README with correct message type for breaking release

.github/workflows/dispatch-test-pr.yml, .github/workflows/dispatch-test-push.yml, .github/workflows/dispatch-test.yml
=> Fix test dispatch

.github/workflows/dispatch-test-pr.yml, docs/classes/SeamMalformedInputError.md, docs/modules.md, package.json, src/index.ts, src/lib/api-error.ts, yarn.lock
=> Throw custom error on malformed input

docs/classes/Seam.md, docs/interfaces/SeamClientOptions.md, docs/modules.md, src/client.ts
Partly closes https://github.com/seamapi/seam-connect/issues/496.
=> Add user agent

docs/interfaces/AccessCodeBase.md, docs/interfaces/ActionAttemptResultTypeMap.md, docs/interfaces/ActionAttemptWithError.md, docs/interfaces/ConnectWebview.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/LockProperties.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/PendingActionAttempt.md, docs/interfaces/SuccessfulActionAttempt.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts
**The tests here will fail** because the internal lib doesn't have these changes merged yet (to merge them, this has to be done first (it seems))
=> fix: Add `has_keypad` property

docs/classes/Seam.md, docs/interfaces/AccessCodeCreateBaseRequest.md, docs/interfaces/AccessCodeCreateOngoingRequest.md, docs/interfaces/AccessCodeCreateScheduledRequest.md, docs/interfaces/AccessCodeUpdateBaseRequest.md, docs/interfaces/ConnectedAccountsDeleteRequest.md, docs/interfaces/DevicesListRequest.md, docs/interfaces/EventsListRequest.md, docs/modules.md, src/types/route-requests.ts
This fixes a weird issue introduced by the merge of the latest PR.
=> fix: Type error and rebuild docs

.github/workflows/npm-semantic-release.yml, docs/classes/Seam.md, docs/interfaces/SeamClientOptions.md, docs/modules.md, package.json, src/client.ts, tests/sentry.test.ts, tsup.config.ts, yarn.lock
- Add Sentry
- Embed Sentry DSN during build
=> feat: Log exceptions to Sentry

src/seam-os/client.ts
the last one didn't bump the release, trying again
=> fix: add missing seam-os routes

docs/classes/Seam.md, docs/interfaces/AccessCodeCreateResponse.md, docs/interfaces/AccessCodeGetResponse.md, docs/interfaces/ActionAttemptCreateResponse.md, docs/interfaces/ActionAttemptGetResponse.md, docs/interfaces/ConnectedAccountsGetResponse.md, docs/interfaces/ConnectedAccountsListResponse.md, docs/interfaces/EventsListResponse.md, docs/interfaces/WebhookGetResponse.md, docs/interfaces/WebhookListResponse.md, docs/modules.md, src/seam-connect/routes.ts, src/types/route-responses.ts
=> Return Access Codes Immediately Instead of Waiting for Action Attempt

.github/workflows/npm-test.yml
Right now if the tests fail here, the status is never reported, but the status should be reported as failing. This update should make that happen 🤞🏻
=> test: Report SDK test status even on failure

docs/interfaces/AccessCodeBase.md, docs/interfaces/ActionAttemptResultTypeMap.md, docs/interfaces/ActionAttemptWithError.md, docs/interfaces/ConnectWebview.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/LockProperties.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/PendingActionAttempt.md, docs/interfaces/SuccessfulActionAttempt.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts
See https://github.com/seamapi/seam-connect/pull/2129
=> fix: Add `supported_code_lengths` property

docs/classes/SeamOS.md, docs/interfaces/SeamOSRouteTypes.Routes.md, docs/modules/SeamOSRouteTypes.md, src/seam-os/client.ts, src/seam-os/routes.ts
Noticed some type failures after merging my last pr. fixing them here
Should probably add `build:docs` to the PR checks
=> fix: seamos type fixes

docs/modules.md, src/types/models.ts
See https://github.com/seamapi/seam-connect/pull/2154
=> fix: Add event.occurred_at

docs/classes/SeamOS.md, docs/interfaces/SeamOSRouteTypes.Routes.md, docs/modules/SeamOSRouteTypes.md, src/seam-os/routes.ts
Would be really nice to automate this ;)
=> fix: Update SeamOS routes

src/cli/index.ts
The last release failed, is there a way to force a release besides this?
=> fix: Force new patch release

README.md, docs/README.md
Current example code does not work as shown in non-es6/ts environment
=> Show correct node require alternative in README

docs/classes/SeamOS.md, src/seam-os/client.ts
Exposes `/events/list` to client
=> Fix: SeamOS - add events.list to client

docs/classes/SeamOS.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/SeamOSRouteTypes.Routes.md, docs/interfaces/TimeBoundAccessCode.md, docs/modules/SeamOSRouteTypes.md, src/seam-os/client.ts, src/seam-os/routes.ts
=> fix: SeamOS Routes Update

docs/classes/SeamOS.md, docs/interfaces/SeamOSRouteTypes.Routes.md, src/seam-os/routes.ts
Matching backend PR https://github.com/seamapi/space-backend/pull/245
=> Fix: Incident - rename type -> incident_type for consistency

docs/classes/SeamOS.md, docs/interfaces/SeamOSRouteTypes.Routes.md, docs/modules/SeamOSRouteTypes.md, src/seam-os/client.ts, src/seam-os/routes.ts
- adds organizations.get_count_summary to seamos client
- updates return object signature of organizations.get_count_summary
=> Add organizations.get_count_summary; update seam space API

docs/interfaces/EventsListRequest.md, src/types/route-requests.ts
Partially closes https://github.com/seamapi/seam-connect/issues/2325
=> Support `connected_account_id` param on `events.list`

docs/modules.md, src/types/models.ts
Also forgot to add a prefix to last commit on location so didn't release 🤦‍♂️
=> fix: Add `critical` to battery status union

docs/classes/Seam.md, docs/interfaces/AccessCodeBase.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/UnmanagedAccessCodeBase.md, docs/interfaces/UnmanagedAccessCodesGetResponse.md, docs/interfaces/UnmanagedAccessCodesListResponse.md, docs/interfaces/UnmanagedOngoingAccessCode.md, docs/interfaces/UnmanagedTimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts
I think this is the best way to have the type work just like `access_codes`, the only changes being `status: set` and `is_managed: false`
=> fix: unmanaged codes type r2

tests/routes.test.ts
I tried to mark them failing, but only skipping them worked.
=> test: Skip failing tests

src/seam-connect/client.ts
Supersedes https://github.com/seamapi/javascript/pull/193/files
=> feat: Use PUT /client_sessions/create

docs/classes/Seam.md, docs/interfaces/EventsListRequest.md, docs/modules.md, src/seam-connect/routes.ts, src/types/route-requests.ts
- feat: Add AccessCodesListRequest type
- feat: Add missing unmanaged access code request types
=> Add missing access code request types

src/types/models.ts
=> fix: Rename yale_acess -> yale

docs/classes/Seam.md, docs/interfaces/EventsListRequest.md, docs/modules.md, src/seam-connect/routes.ts, src/types/route-requests.ts
This is basically the same thing as `accessCodes.unmanaged.update`, but it uses an action attempt
See here:
https://github.com/seamapi/seam-connect/pull/3019
Need this PR for this:
https://github.com/seamapi/console/pull/532
=> feat: Add `accessCodes.unmanaged.convertToManaged`

.github/workflows/npm-test.yml
At least until tests are passing again.
=> ci: Disable cron tests

docs/interfaces/AccessCodeBase.md, docs/interfaces/ActionAttemptResultTypeMap.md, docs/interfaces/ActionAttemptWithError.md, docs/interfaces/ClientSession.md, docs/interfaces/ConnectWebview.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/Device.md, docs/interfaces/DeviceModel.md, docs/interfaces/DeviceProvider.md, docs/interfaces/LockProperties.md, docs/interfaces/ManagedAccessCodeBase.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/PendingActionAttempt.md, docs/interfaces/SeamError.md, docs/interfaces/SeamWarning.md, docs/interfaces/SuccessfulActionAttempt.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/UnmanagedAccessCodeBase.md, docs/interfaces/UnmanagedOngoingAccessCode.md, docs/interfaces/UnmanagedTimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts, tests/routes.test.ts
- 2fa30e9 feat: Add isNoiseSensorDevice
- b9a5964 feat: Add NoiseSensorDevice and NoiseSensorDeviceType
- bca69fd feat: Add isLockDevice
- 1a67016 feat: Add CommonDevice
=> Device type updates and type guards

docs/interfaces/AccessCodeBase.md, docs/interfaces/ActionAttemptResultTypeMap.md, docs/interfaces/ActionAttemptWithError.md, docs/interfaces/ClientSession.md, docs/interfaces/ConnectWebview.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/Device.md, docs/interfaces/DeviceModel.md, docs/interfaces/LockProperties.md, docs/interfaces/ManagedAccessCodeBase.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/PendingActionAttempt.md, docs/interfaces/SuccessfulActionAttempt.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/UnmanagedAccessCodeBase.md, docs/interfaces/UnmanagedOngoingAccessCode.md, docs/interfaces/UnmanagedTimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts
- feat: Add online to UnmanagedDeviceProperties
- fix: Move manufacturer to CommonDeviceProperties
=> Unmanage device online status

docs/interfaces/AccessCodeBase.md, docs/interfaces/ActionAttemptResultTypeMap.md, docs/interfaces/ActionAttemptWithError.md, docs/interfaces/ClientSession.md, docs/interfaces/ConnectWebview.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/Device.md, docs/interfaces/DeviceModel.md, docs/interfaces/DeviceProvider.md, docs/interfaces/LockProperties.md, docs/interfaces/ManagedAccessCodeBase.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/PendingActionAttempt.md, docs/interfaces/SuccessfulActionAttempt.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/UnmanagedAccessCodeBase.md, docs/interfaces/UnmanagedOngoingAccessCode.md, docs/interfaces/UnmanagedTimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts
- feat: Add is_managed to Device and UnmanagedDevice
=> feat: Add is_managed to Device and UnmanagedDevice

docs/interfaces/AccessCodeCreateBaseRequest.md, docs/interfaces/AccessCodeCreateMultipleOngoingRequest.md, docs/interfaces/AccessCodeCreateMultipleScheduledRequest.md, docs/interfaces/AccessCodeCreateOngoingRequest.md, docs/interfaces/AccessCodeCreateScheduledRequest.md, docs/interfaces/AccessCodeUpdateBaseRequest.md, docs/interfaces/DeviceProvidersListRequest.md, docs/interfaces/DevicesListRequest.md, docs/interfaces/EventsListRequest.md, docs/modules.md, src/types/route-requests.ts
w.r.t. https://github.com/seamapi/api-docs/issues/102
=> Update `devices.list` request params

docs/classes/Seam.md, src/seam-connect/client.ts
Was reverted before because of issue on API. That has now been resolved.
=> fix: Send authorization header with client session token

docs/interfaces/AccessCodeCreateBaseRequest.md, docs/interfaces/AccessCodeCreateMultipleOngoingRequest.md, docs/interfaces/AccessCodeCreateMultipleScheduledRequest.md, docs/interfaces/AccessCodeCreateOngoingRequest.md, docs/interfaces/AccessCodeCreateScheduledRequest.md, docs/interfaces/AccessCodeUpdateBaseRequest.md, docs/interfaces/ConnectWebviewCreateRequest.md, docs/interfaces/ConnectWebviewDeleteRequest.md, docs/interfaces/ConnectedAccountsDeleteRequest.md, docs/interfaces/ConnectedAccountsGetRequest.md, docs/interfaces/DeviceProvidersListRequest.md, docs/interfaces/DevicesListRequest.md, docs/interfaces/EventGetRequest.md, docs/interfaces/EventsListRequest.md, docs/modules.md, src/types/route-requests.ts
Add new flag to ConnectWebview create.
=> Add automatically_manage_new_devices to ConnectWebview Create

docs/interfaces/AccessCodeBase.md, docs/interfaces/AccessCodeError.md, docs/interfaces/ActionAttemptResultTypeMap.md, docs/interfaces/ActionAttemptWithError.md, docs/interfaces/BaseThermostatDeviceProperties.md, docs/interfaces/ClientSession.md, docs/interfaces/ConnectWebview.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/ConnectedAccountError.md, docs/interfaces/Device.md, docs/interfaces/DeviceError.md, docs/interfaces/DeviceModel.md, docs/interfaces/DeviceProvider.md, docs/interfaces/LockProperties.md, docs/interfaces/ManagedAccessCodeBase.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/PendingActionAttempt.md, docs/interfaces/SeamError.md, docs/interfaces/SeamWarning.md, docs/interfaces/SuccessfulActionAttempt.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/UnmanagedAccessCodeBase.md, docs/interfaces/UnmanagedOngoingAccessCode.md, docs/interfaces/UnmanagedTimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts
me === 🤡 
another kick in the butt to use public types
=> fix: fix thermostat device types 

docs/interfaces/AccessCodeBase.md, docs/interfaces/AccessCodeCreateBaseRequest.md, docs/interfaces/AccessCodeCreateMultipleOngoingRequest.md, docs/interfaces/AccessCodeCreateMultipleScheduledRequest.md, docs/interfaces/AccessCodeCreateOngoingRequest.md, docs/interfaces/AccessCodeCreateScheduledRequest.md, docs/interfaces/AccessCodeUpdateBaseRequest.md, docs/interfaces/ClientSession.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/ConnectedAccountError.md, docs/interfaces/DeviceModel.md, docs/interfaces/EventGetRequest.md, docs/interfaces/EventsListRequest.md, docs/interfaces/ManagedAccessCodeBase.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/UnmanagedAccessCodeBase.md, docs/interfaces/UnmanagedOngoingAccessCode.md, docs/interfaces/UnmanagedTimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts, src/types/route-requests.ts
In relation to https://github.com/seamapi/javascript/issues/281
=> Add `appearance` and `allow_external_modification` to relevant access code objects and methods

docs/classes/Seam.md, docs/interfaces/AccessCodeCreateBaseRequest.md, docs/interfaces/AccessCodeCreateMultipleOngoingRequest.md, docs/interfaces/AccessCodeCreateMultipleScheduledRequest.md, docs/interfaces/AccessCodeCreateOngoingRequest.md, docs/interfaces/AccessCodeCreateScheduledRequest.md, docs/interfaces/AccessCodeUpdateBaseRequest.md, docs/interfaces/ConnectWebviewCreateRequest.md, docs/interfaces/ConnectWebviewDeleteRequest.md, docs/interfaces/ConnectedAccountsDeleteRequest.md, docs/interfaces/ConnectedAccountsGetRequest.md, docs/interfaces/DeviceProvidersListRequest.md, docs/interfaces/DevicesListRequest.md, docs/interfaces/EventGetRequest.md, docs/interfaces/EventsListRequest.md, docs/modules.md, src/seam-connect/routes.ts, src/types/route-requests.ts, tests/routes.test.ts
=> feat: Add `setFanMode`

docs/interfaces/AccessCodeBase.md, docs/interfaces/AccessCodeError.md, docs/interfaces/ActionAttemptResultTypeMap.md, docs/interfaces/ActionAttemptWithError.md, docs/interfaces/BaseThermostatDeviceProperties.md, docs/interfaces/ClientSession.md, docs/interfaces/ConnectWebview.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/ConnectedAccountError.md, docs/interfaces/Device.md, docs/interfaces/DeviceError.md, docs/interfaces/DeviceModel.md, docs/interfaces/DeviceProvider.md, docs/interfaces/LockProperties.md, docs/interfaces/ManagedAccessCodeBase.md, docs/interfaces/NoiseSensorDeviceProperties.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/PendingActionAttempt.md, docs/interfaces/SeamError.md, docs/interfaces/SeamWarning.md, docs/interfaces/SuccessfulActionAttempt.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/UnmanagedAccessCodeBase.md, docs/interfaces/UnmanagedOngoingAccessCode.md, docs/interfaces/UnmanagedTimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts
=> feat: Add `noise_level_decibels` to `NoiseSensorDeviceProperties`

docs/interfaces/AccessCodeBase.md, docs/interfaces/AccessCodeError.md, docs/interfaces/ActionAttemptResultTypeMap.md, docs/interfaces/ActionAttemptWithError.md, docs/interfaces/BaseThermostatDeviceProperties.md, docs/interfaces/ClientSession.md, docs/interfaces/ConnectWebview.md, docs/interfaces/ConnectedAccount.md, docs/interfaces/ConnectedAccountError.md, docs/interfaces/Device.md, docs/interfaces/DeviceError.md, docs/interfaces/DeviceModel.md, docs/interfaces/DeviceProvider.md, docs/interfaces/LockProperties.md, docs/interfaces/ManagedAccessCodeBase.md, docs/interfaces/NoiseSensorDeviceProperties.md, docs/interfaces/OngoingAccessCode.md, docs/interfaces/PendingActionAttempt.md, docs/interfaces/SeamError.md, docs/interfaces/SeamWarning.md, docs/interfaces/SuccessfulActionAttempt.md, docs/interfaces/TimeBoundAccessCode.md, docs/interfaces/UnmanagedAccessCodeBase.md, docs/interfaces/UnmanagedOngoingAccessCode.md, docs/interfaces/UnmanagedTimeBoundAccessCode.md, docs/interfaces/UserIdentifier.md, docs/interfaces/Webhook.md, docs/modules.md, src/types/models.ts
=> feat: Add `currently_triggering_noise_threshold_ids`
